Support Joining a Game
8th-Rank-Pawns/chess-app pull request #19
Opened 2017-02-09 01:18 UTC by rouxcaesar

🚨  🚨  🚨  🚨  🚨  🚨  🚨  🚨  🚨  🚨 
🚧  UNDER CONSTRUCTION 🚧

2017-02-16 20:06 UTC, dtrypt reviewed
You didn't specify what game your trying to update in the test. You need something like id: game.id after the put :update. Also use :game instead of :fullgame because :fullgame is already populated with players. Here's what I think the test should look like:
  
```
describe 'games#update action' do
    it 'should successfully update the game black_player to the currently logged-in user id' do
      game = FactoryGirl.create(:game, black_player: nil)
      user = FactoryGirl.create(:user)
      put :update, id: game.id, game: { black_player: user.id }
      expect(response).to have_http_status(:success)
      game.reload
      expect(game.black_player).to eq(user.id)
    end
  end

```
It looks like there's some middleware issues with devise and rspec so you'll have to add a line to the rails_helper, see: http://stackoverflow.com/questions/38421853/why-is-my-rspec-not-loading-devisetestcontrollerhelpers

Lastly, I tried running the test and it's not successful. So I think that means that your update action in the games controller is not working properly so that will need to be fixed. I haven't had time to fully look into it...

UPDATE: It's failing because the user isn't signed in. This should work:

```
describe 'games#update action' do
    it 'should successfully update the game black_player to the currently logged-in user id' do
      game = FactoryGirl.create(:game, black_player: nil)
      user = FactoryGirl.create(:user)
      sign_in user
      put :update, id: game.id, game: { black_player: user.id }
      game.reload
      expect(game.black_player).to eq(user.id)
    end
  end

```
I've only reviewed your tests. Haven't looked at the rest of your code yet.

2017-02-17 21:05 UTC, sungwon commented
Looks good so far! I'll take another look after the spec changes @trustinruss suggested.

2017-02-19 16:03 UTC, rouxcaesar commented
I've made the changes suggested by Russ to the PR and it should be good for another review.

2017-02-19 16:18 UTC, sungwon requested changes
I noticed that the #create method in the GamesController doesn't update the game by setting the white player as the current user. It's not part of the scope of your task, but if you'd like to take care of that while you're in the GamesController anyway, that'd be cool. I added a card for it in the backlog.

2017-02-19 16:18 UTC, sungwon commented on config/routes.rb
> +  get 'game', to: 'games#show'
This seems to be redundant with line 4.

2017-02-19 16:18 UTC, sungwon commented on app/controllers/games_controller.rb
> +    if @game.black_player != current_user
Is this just a sanity check to potentially avoid an unnecessary database call? cool.

2017-02-19 20:03 UTC, sungwon commented
Ah, I see you've already made a card for create game. Never mind about pulling it into this merge request then.

2017-02-25 22:33 UTC, rouxcaesar commented on app/controllers/games_controller.rb
> +    if @game.black_player != current_user
Yes it is!

2017-02-25 22:34 UTC, rouxcaesar commented on config/routes.rb
> +  get 'game', to: 'games#show'
Removed!

2017-02-25 23:03 UTC, sungwon approved these changes

2017-02-26 06:28 UTC, dtrypt approved these changes

2017-02-26 20:45 UTC, merged