Castle
8th-Rank-Pawns/chess-app pull request #30
Opened 2017-03-04 03:56 UTC by trustinruss

- Adding castling that follows this guide:
http://www.mark-weeks.com/aboutcom/ble14cas.htm
- Added a 'castle' field to pieces model which is for checking is the kings/rooks have been moved prior to castling.
- Moved most logic from piece model to pieces_helper.
- Refactored move_to! & capture logic.
- Had to use a lot of methods to appease rubocops complexity checks, which made it even more complex imo =/.
- Added an alert pop-up to the view for invalid moves.
- Added tests for castling and my backlogged tests for updating pieces.

- Please review this PR before PRs that come after this, or there will be tons of merge conflicts because I changed A LOT of files.
- I need to add "prevent yourself from moving into check" to wrap up the last 2 conditions. I'm going to submit an additional PR for that after we merge in Leslie's part.

2017-03-05 16:37 UTC, sungwon requested changes
Epic pull request! Nice work

2017-03-05 16:37 UTC, sungwon commented on app/helpers/pieces_helper.rb
>  module PiecesHelper
Good idea refactoring this out into a Helper

2017-03-05 16:37 UTC, sungwon commented on app/models/game.rb
> +    king = King.find_by(game: self, color: color)
Nice. This is neater than .where(....).first

2017-03-05 16:37 UTC, sungwon commented on app/models/king.rb
> +    rook = instance_variable_get("@#{color}_queen_rook")
Whoa! Nice meta-programming. 

How about using this technique to reduce the code duplication and combine queen_side_castle_check and king_side_castle_check into, say: 

```ruby
def castle_check(color, side)
  rook = instance_variable_get("@#{color}_#{side}_rook")
...
```

2017-03-05 16:37 UTC, sungwon commented on app/models/king.rb
> +  def perform_queenside_castling(color)
Combine with kingside into one perform_castling method just like castle_check

2017-03-05 16:37 UTC, sungwon commented on app/views/games/show.html.erb
> +              alert("Illegal move. Try again.");
Good idea.

2017-03-05 16:37 UTC, sungwon commented on app/helpers/pieces_helper.rb
> +  def can_capture?(new_x, new_y)
I think we should rename this to just `capture`.  `can_capture?` sounds like it just returns a boolean if it is able to capture, but it has the unexpected side effect of actually performing the capture and updating the piece position. If we say `capture` we know we are trying to capture, but simply return false if we can't.

2017-03-05 21:58 UTC, koglesby reviewed
Awesome castling logic - works well, and nice refactoring. I'm not sure why the chess#index tests are failing though

2017-03-08 03:57 UTC, trustinruss commented
To my surprise I was getting the issue with the same 2 tests that were failing even after rebasing with the latest merge. Data from past tests were persisting into new tests. It seems like this is a common issue and some digging pointed me to "database_cleaner" - a ruby gem that allows you to reset the database before running tests. Seems like this is the best solution and everything works properly.

2017-03-08 13:41 UTC, sungwon approved these changes

2017-03-08 13:42 UTC, sungwon commented
Good find with that database_cleaner. That's weird, I was under the impression that the test database was cleared automatically after every test session.

2017-03-08 18:29 UTC, koglesby approved these changes

2017-03-08 19:17 UTC, merged