Finish check method. NOT FINISHED YET.
8th-Rank-Pawns/chess-app pull request #32
Opened 2017-03-05 19:19 UTC by LesleyPark

king.horizontal_position and king.vertical position are now storing locations, but now getting the following issues:

1.) NoMethodError (undefined method `-' for nil:NilClass):
  app/models/pawn.rb:3:in `valid_move?'
  app/models/game.rb:28:in `block in check?'
  app/models/game.rb:27:in `check?'
  app/models/piece.rb:21:in `move_to!'
  app/controllers/pieces_controller.rb:4:in `update'

2.) Failures when running bundle exec rspec:

  2a.) ChessController chess#index action should list games with less than 2 players as available
     Failure/Error: expect(games.count).to eq(1)
     
       expected: 1
            got: 4
     
       (compared using ==)
     # ./spec/controllers/chess_controller_spec.rb:15:in `block (3 levels) in <top (required)>'

  2b.) ChessController chess#index action should not list games with 2 players as available
     Failure/Error: expect(games.count).to eq(0)
     
       expected: 0
            got: 3
     
       (compared using ==)
     # ./spec/controllers/chess_controller_spec.rb:23:in `block (3 levels) in <top (required)>'

2017-03-08 04:00 UTC, dtrypt reviewed
Is this PR ready to be reviewed?

2017-03-08 06:27 UTC, LesleyPark commented
@trustinruss, more or less. Still tinkering with some things because one of the tests in the game_controller spec broke, but if you (or anyone else) has any idea what went wrong there, I'm all ears.

2017-03-08 19:47 UTC, trustinruss commented
Is this the error?
```
GamesController games#show action should return a 404 error if the game is not found
Failure/Error: flash[:notice] = 'Black King Check!' if @game.check?('black')
```
Should fix if you add a `return` to the line `render text: 'Not Found', status: :not_found if @game.blank?` so that a game that doesn't exist kills the method rather than running through @game.check. It can't run methods on games that don't exist. The return should have been there from the start.

2017-03-09 05:40 UTC, LesleyPark commented
@trustinruss, that fixed it! Thanks (and there's another mistake I hopefully won't be making again, hah)! I'm getting a strange "trailing whitespace error" on config/routes.rb which makes no sense since I haven't touched the file. It goes away when I delete the spacing at line 6 but I feel like we should probably keep that...

2017-03-09 19:57 UTC, dtrypt commented
@LesleyPark haven't tested it but I'm guessing you have an indentation at line 6. Delete the indentation rather than the line.
When this PR is ready to be looked at, could you update the description to FINISHED. Thanks!

2017-03-09 20:37 UTC, trustinruss commented on app/models/piece.rb
> +        enemy_piece.destroy
This makes more sense, but if you do this you'll have to fix code that relies on piece position values going to nil throughout the codebase.... and any tests. If this seems like a lot of work then I would just change this line back... but then you would have to add a condition(s) to models/game.rb that excludes nil value pieces from running through the loop in the check?(color) method.

For example, here's one spot that relies on pieces position becoming nil:
In games_controller.rb:
`  def show
    @game = Game.find_by_id(params[:id])

    data = params[:p_type]

    until data.nil?
      @game.pieces.where(type: 'Pawn', vertical_position: 1).first.try(:update_attributes, type: data)
      @game.pieces.where(type: 'Pawn', vertical_position: 8).first.try(:update_attributes, type: data)
      data = params[:p_type] = nil
      redirect_to game_path(@game)
    end`

2017-03-09 21:09 UTC, koglesby commented on app/models/piece.rb
> +        enemy_piece.destroy
I don't see a problem with this. The example above doesn't rely on pieces position becoming nil; it is referring to the data which comes from a pawn promotion piece selection. It also functions by updating the piece type, as opposed to removing it from the board and replacing it. I didn't notice any test fails from switching to destroy method either..

2017-03-09 21:31 UTC, trustinruss commented on app/models/piece.rb
> +        enemy_piece.destroy
Okay. That makes sense. Hopefully we can use the destroy method and have everything still working then.

2017-03-09 21:36 UTC, koglesby requested changes
Nice, triggers the flash notice as it supposed to. Noticed a little bug where the flash message persists on the first move out of check

2017-03-09 21:36 UTC, koglesby commented on app/controllers/games_controller.rb
> +    flash[:notice] = 'White King Check!' if @game.check?('white')
Right now the flash notice stays up after the first move to get out of check. To fix that, you can set it to nil when not in check.

 if @game.check?('black')
     flash[:notice] = 'Black King Check!'
    elsif @game.check?('white')
      flash[:notice] = 'White King Check'
    else
     flash[:notice] = nil
    end

2017-03-09 21:36 UTC, koglesby commented on app/views/games/show.html.erb
> +          // window.location.reload();
Don't forget to re-enable the page reload!

2017-03-09 22:53 UTC, LesleyPark commented on app/models/piece.rb
> +        enemy_piece.destroy
@trustinruss, aside from the game_controller spec, the tests were running fine for me as well. And nope, no indentation on config/routes.rb. When I'm on line 6, a left error takes me up to line 5 and a right arrow takes me down to line 7. Deleting the space altogether makes the error go away as does commenting it out, but I'm just going to leave it as is and ignore Rubocop on that one...

2017-03-09 23:26 UTC, trustinruss commented on app/models/piece.rb
> +        enemy_piece.destroy
Really? That's strange...I pulled the code in and tested it right now. I'm seeing an indented line 6. If I place the cursor at line 6, it doesn't line up with the cursor at line 9 (which is another empty line). Deleting the indentation fixed the trailing whitespace error for me. If it still doesn't work, I'll fix it in my next pull request.

I guess if it's still broken for you, someone else can fix it in their next PR.

2017-03-09 23:28 UTC, trustinruss commented on app/controllers/games_controller.rb
> -    render text: 'Not Found', status: :not_found if @game.blank?
Just add return to this line.
`return` render text: 'Not Found', status: :not_found if @game.blank?`

2017-03-09 23:29 UTC, trustinruss commented on app/controllers/games_controller.rb
> +    flash[:notice] = 'White King Check!' if @game.check?('white')
Nice catch

2017-03-09 23:31 UTC, dtrypt requested changes
I think it would be best to rebase to the latest master branch before making the changes we suggested.

2017-03-10 04:18 UTC, LesleyPark commented on app/controllers/games_controller.rb
> +    flash[:notice] = 'White King Check!' if @game.check?('white')
@koglesby, interestingly when I did this, Rubocop got hissy about my conditional variables. But when I changed it to:

flash[:notice] = 'Black King Check!' if @game.check?('black')
flash[:notice] = 'White King Check' if @game.check?('white')

sans flash[:notice] = nil, the bug stopped happening.

2017-03-10 04:21 UTC, LesleyPark commented on app/controllers/games_controller.rb
> +    flash[:notice] = 'White King Check!' if @game.check?('white')
@koglesby, never mind. Was able to reproduce it. Strange. Looks like it only triggers sometime. Hmm. Should I just overrule Rubocop on this one?

2017-03-10 04:34 UTC, LesleyPark commented
@trustinruss, I was going to handle all the new stuff with a merge after everything had been okay-ed. Does that not work here or?

2017-03-10 07:10 UTC, dtrypt approved these changes

2017-03-10 12:44 UTC, sungwon approved these changes

2017-03-10 12:44 UTC, sungwon commented on app/controllers/games_controller.rb
> +      return redirect_to game_path(@game)
the return here isn't necessary (but probably doesn't hurt either)

2017-03-10 12:44 UTC, sungwon commented on app/helpers/pieces_helper.rb
> +      # @chess_piece.update_attributes(horizontal_position: nil, vertical_position: nil)
next time this file is touched, let's take out the comment.

2017-03-10 18:17 UTC, LesleyPark commented on app/controllers/games_controller.rb
> +      return redirect_to game_path(@game)
@trustinruss and I paired on this last night. We found that not having the return there somehow broke the test for pawn promotion in the game controller spec.

2017-03-10 22:08 UTC, koglesby approved these changes

2017-03-10 22:13 UTC, merged