Assigned white player, fixed tests, improved UI
8th-Rank-Pawns/chess-app pull request #35
Opened 2017-03-07 03:27 UTC by trustinruss

- Full games now work in the UI as they are supposed to.
- You can join/spectate games and see the players in the game already.
- User that creates a game becomes white_player.
- Got all the rspec tests working properly finally.
Was having a problem where sometimes a factory item persists in the testing database and you need to run
`bundle exec rake db:test:prepare` to reset it.
**Please take a look at this asap** and test out the changes. Once this is approved the "Castle" PR should pass testing.

2017-03-07 21:18 UTC, koglesby requested changes
Nice, I like the south park default user image - the top nave looks a lot better for non-fb sign in. I like how you can join a game with yourself, too, and the spectate feature is a cool idea. 
Still needs to authenticate user before creating a new game, otherwise you run into an error when you try to create a game when you're not signed in

2017-03-08 00:58 UTC, sungwon commented
@koglesby Nice catch. 
@trustinruss Looks good. I only wonder about the performance of `@full_games = Game.all - @available_games`, but we can worry about optimization later. Spectate is a great idea for a feature. I'll approve after the changes @koglesby  requested.

2017-03-08 01:12 UTC, trustinruss commented
@koglesby @sungwon Nice catch! fixed the issue.

2017-03-08 01:27 UTC, koglesby approved these changes

2017-03-08 02:13 UTC, sungwon approved these changes

2017-03-08 02:21 UTC, merged